### ISSUE TITLE
Stdlib Dependency

### ISSUE THREAD

**Issue by danjng** [unibet/puppet-forge_server#1]
You should probably document that it has a dependency on puppetlabs-stdlib.

I ran into the issue on first puppet run:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type anchor at /etc/puppetlabs/puppet/environments/.../modules/forge_server/manifests/init.pp:81 on node ...

**Comment by i11** [comment]
Hi,

Please see https://github.com/unibet/puppet-forge_server/blob/master/metadata.json. There is stdlib dependency defined.

**Comment by danjng** [comment]
My mistake. I was using r10k and did not know that it does not pull dependent modules.

I guess you learn something new every day!

Thanks for pointing that out, i11.
